name: dav-t2i
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.10.13
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - accelerate==1.6.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiosignal==1.3.2
      - appdirs==1.4.4
      - args==0.1.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - braceexpand==0.1.7
      - cachetools==5.3.3
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - clint==0.5.1
      - contextlib2==21.6.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - datasets==2.20.0
      - diffusers==0.17.1
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - dreamsim==0.2.1
      - einops==0.8.1
      - exceptiongroup==1.2.2
      - fairscale==0.4.13
      - filelock==3.13.1
      - fonttools==4.54.1
      - frozenlist==1.5.0
      - fsspec==2024.2.0
      - ftfy==6.3.1
      - gitdb==4.0.11
      - gitpython==3.1.42
      - google-auth==2.28.1
      - hf-xet==1.1.3
      - hpsv2==1.2.0
      - huggingface-hub==0.23.5
      - idna==3.6
      - image-reward==1.5
      - importlib-metadata==7.0.1
      - inflect==6.0.4
      - iniconfig==2.1.0
      - jinja2==3.1.3
      - jmespath==1.0.1
      - joblib==1.5.1
      - kiwisolver==1.4.7
      - lpips==0.1.4
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - ml-collections==0.1.1
      - mpmath==1.3.0
      - multidict==6.2.0
      - multiprocess==0.70.16
      - networkx==3.2.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - open-clip-torch==2.32.0
      - openai-clip==1.0.1
      - packaging==24.2
      - pandas==2.2.3
      - peft==0.11.1
      - pillow==10.2.0
      - pluggy==1.5.0
      - propcache==0.3.1
      - protobuf==3.20.3
      - psutil==5.9.8
      - pyarrow==19.0.1
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pydantic==1.10.9
      - pyparsing==3.1.1
      - pytest==7.2.0
      - pytest-split==0.8.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2023.12.25
      - requests==2.32.3
      - rsa==4.9
      - safetensors==0.5.3
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - sentencepiece==0.2.0
      - sentry-sdk==1.40.6
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - sympy==1.12
      - threadpoolctl==3.6.0
      - timm==0.6.13
      - tokenizers==0.19.1
      - tomli==2.2.1
      - torch==2.2.1
      - torchvision==0.17.1
      - tqdm==4.67.1
      - transformers==4.41.2
      - triton==2.2.0
      - typing-extensions==4.10.0
      - tzdata==2025.2
      - urllib3==1.26.11
      - wandb==0.16.3
      - wcwidth==0.2.13
      - webdataset==0.2.111
      - xxhash==3.5.0
      - yarl==1.18.3
      - zipp==3.17.0
